
  

services:
  user_server:
    build: .
    command: uvicorn user_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # Load variables for Docker services
    environment:
      - PYTHONUNBUFFERED=1
    # Remove the volume mount for .env - not needed anymore

  seller_server:
    build: .
    command: uvicorn seller_main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1


  
  buyer_server:
    build: .
    command: uvicorn buyer_main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1

